name: Build and Analyze Spotube (SonarQube)

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necesario para SonarQube

      # Instala Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6' # Usa la versión de Flutter que necesite Spotube

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Project
        run: flutter build apk --debug

      # Escaneo con SonarQube (necesita sonar-project.properties en la raíz)
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
